name: Automated tests

on:
  push

#Задачи к выполнению
jobs:
  #Задача
  lint:
    runs-on: ubuntu-latest
    #шаги к задаче
    steps:
      - name: Checkout repository #название шагов
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run Docker Composer
        run: |
          cd docker;
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} > .env;
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env;
          echo POSTGRES_DB_AUTH=${{ secrets.POSTGRES_DB_AUTH }} >> .env;
          echo POSTGRES_DB_UNIVERSITY=${{ secrets.POSTGRES_DB_UNIVERSITY }} >> .env;
          echo AUTH_SERVICE_INTERNAL_URL=${{ secrets.AUTH_SERVICE_INTERNAL_URL }} >> .env;
          echo AUTH_SERVICE_API_URL=${{ secrets.AUTH_SERVICE_API_URL }} >> .env;
          echo UNIVERSITY_SERVICE_INTERNAL_URL=${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }} >> .env;
          echo UNIVERSITY_SERVICE_API_URL=${{ secrets.UNIVERSITY_SERVICE_API_URL }} >> .env;
          docker compose up -d
          continue-on-error: true
      - name: Run tests
        run:
         pytest --alluredir=allure-results #запускаем тесты и сохраняем результаты в папку
        continue-on-error: true
      - name: Show postgres-auth logs if failed
        if: failure()
        run: docker logs postgres-auth || true
      - name: Upload Allure results  # Загружаем результаты тестов в GitHub Actions
        if: always()  # Загружаем файлы независимо от успеха/неуспеха тестов
        uses: actions/upload-artifact@v4
        with:
          name: allure-results  # Название артефакта
          path: allure-results
          retention-days: 1# Путь к файлам отчета

  generate-report:
    runs-on: ubuntu-latest
    needs: tests
    name: Generate report
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: Install allure
        run:
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          && sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts #скачиваем все артефакты, которые были ранее сгенерированы
        uses: actions/upload-artifact@v4
      - name: Allure generate
        run: allure generate -c allure-results -o _site #генерация результатов
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site  # Название артефакта
          path: _site
          retention-days: 1


  publish-report:  # Джоба для публикации Allure-отчета на GitHub Pages
    name: Publish report
    runs-on: ubuntu-latest
    needs: generate-report
    steps:
      - name: Download all workflow run artifacts #скачиваем все артефакты, которые были ранее сгенерированы
        uses: actions/upload-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4








